### ISSUE TITLE
"Fetched-v14.16.0-win-x64 Error! 404 Not Found"

### ISSUE THREAD

**Issue by NyboTV** [vercel/pkg-fetch#127] opened 2021-03-25 16:54 UTC
**### Console:**
(My Command:) "PS P:\Dieser PC\Desktop\Fs19Dummy\1Discord-Bot\AutoUpdater\player\autoupdaterv3\NyboTV> pkg . --targets=node14-win-x64
> pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.16.0-win-x64     [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.7/uploaded-v2.7-node-v14.16.0-win-x64
> Asset not found by direct link:
  {"tag":"v2.7","name":"uploaded-v2.7-node-v14.16.0-win-x64"}
> Not found in GitHub releases:
  {"tag":"v2.7","name":"uploaded-v2.7-node-v14.16.0-win-x64"}
> Building base binary from source:
  built-v14.16.0-win-x64
> Cloning Node.js repository from GitHub...
  git                          [                    ] 0%
> Error! Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
PS P:\Dieser PC\Desktop\Fs19Dummy\1Discord-Bot\AutoUpdater\player\autoupdaterv3\NyboTV>

**Comment by hipstersmoothie** [comment] 2021-03-25 16:59
duplicate of #1097

**Closed by hipstersmoothie** 2021-03-25 16:59 UTC
