### ISSUE TITLE
Binary not found 

### ISSUE THREAD

**Issue by nrfribeiro** [vercel/pkg-fetch#128] opened 2021-03-25 17:20 UTC
Hi,
i'm getting the error when downloading https://github.com/zeit/pkg-fetch/releases/download/v2.7/uploaded-v2.7-node-v14.16.0-alpine-x64
I notice is a new release :)

pkg@4.5.0
> Fetching base Node.js binaries to PKG_CACHE_PATH

> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.7/uploaded-v2.7-node-v14.16.0-alpine-x64
> Asset not found by direct link:
  {"tag":"v2.7","name":"uploaded-v2.7-node-v14.16.0-alpine-x64"}
> Not found in GitHub releases:
  {"tag":"v2.7","name":"uploaded-v2.7-node-v14.16.0-alpine-x64"}

**Comment by robertsLando** [comment] 2021-03-25 17:25
Duplicate of #127

**Closed by robertsLando** 2021-03-25 17:25 UTC
