### ISSUE TITLE
Build on FreeBSD from Source

### ISSUE THREAD

**Issue by marcotuna** [vercel/pkg-fetch#49] opened 2018-09-25 21:19 UTC
I tried to compile my project directly from a FreeBSD machine however pkg-fetch is not executing ./configure on the NodeJS source code for some reason, I checked the code of pkg-fetch and the ./configure is present on the Unix compileOnUnix function but it is not being executed. If I clone the NodeJS repository and clone it by myself it works.

```
git clone https://github.com/nodejs/node
git checkout v8.11.3
cd node
./configure
gmake
```

Output from pkg (I renamed pkg to pkg-node to not conflict with FreeBSD native pkg binary)

```
root@server:~/nodedemoproject # pkg-node . --target node8-freebsd-x64 -b
> pkg@4.3.4
> Building base binary from source:
  built-v8.11.3-freebsd-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v8.11.3
> Applying patches
> Compiling Node.js from sources...
  gmake                        [                    ] 0%Makefile:102: *** Missing or stale config.gypi, please run ./configure.  Stop.
  gmake                        [====================] 100%
> Error! Error: gmake failed with code 2
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pkg/node_modules/pkg-fetch/lib-es5/spawn.js:73:23)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)`
```

**Comment by marcotuna** [comment] 2018-09-28 10:28
Is there any way I can generate a node build for FreeBSD x64 and be uploaded to this repository?

**Comment by hipstersmoothie** [comment] 2021-02-28 23:26
@leerob this is a dupe of #39 and can be closed

**Closed** 2021-03-01 14:44 UTC
