### ISSUE TITLE
Error! No available node version satisfies 'node12.2.0'

### ISSUE THREAD

**Issue by QuickJack** [vercel/pkg-fetch#174] opened 2021-04-30 08:53 UTC
pkg -it node12.2.0-linux-armv7 index.js -o app
> pkg@5.1.0
> Error! No available node version satisfies 'node12.2.0'

Today, my ci build failed with the above mentioned error. Why have the existing arm7 images been removed? Why does V3.0 not provide any images for armv7 anymore?

**Comment by robertsLando** [comment] 2021-04-30 08:58
Use `node12` instead

**Comment by QuickJack** [comment] 2021-04-30 09:30
I already tried node 12. But it's not available anymore.

**Comment by robertsLando** [comment] 2021-04-30 09:45
Closing as a duplicate of #109

**Closed by robertsLando** 2021-04-30 09:45 UTC

**Comment by QuickJack** [comment] 2021-04-30 10:55
I have solved the issue by installing pkg as follows:

`npm install -g pkg@4.5.1`

Yes, it's still the outdated Node 12.2.0. But it's working.
