### ISSUE TITLE
ARMv7 binaries not available for Node.js 14

### ISSUE THREAD

**Issue by renkei** [vercel/pkg-fetch#109] opened 2020-11-13 09:43 UTC
Node.js 14.15 LTS is out and recommended by the Node,js team. Unfortunately, the patched Node.js binaries available for pkg are currently limited to the outdated versions 14.0.0 and 14.4.0 and ARM binaries are completely missing.

**Comment by Fossil01** [comment] 2020-11-16 14:00
I would like to have these as well.

**Comment by JoahTheron** [comment] 2020-12-23 12:57
me too. but what i don't understand is why "pkg . -t node12.2.0-linux-armv7" doesn't find the packages.

It always tries to resolve to windows-armv7

**Comment by schlomo** [comment] 2021-02-01 19:02
Same problem here on Mac:

```sh
$ uname -a
Darwin myhost 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
$ npx pkg --out-path dist --targets node12.2.0-linux-armv7 --public some.js
> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.2.0-macos-armv7  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-macos-armv7
...
```

**Comment by Bande11a** [comment] 2021-02-13 22:55
I'm also trying to compile V14 for ArmV7 and mine just gets stuck on make 0%

`> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.4.0-linux-armv7  [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v14.4.0-linux-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v14.4.0-linux-armv7"}
> Building base binary from source:
  built-v14.4.0-linux-armv7
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v14.4.0
> Applying patches
> Compiling Node.js from sources...
  make                         [                    ] 0%^C
`

**Comment by renkei** [comment] 2021-02-22 22:19
Great, it seems to go on now here:
**NPM:** [@jesec/pkg](https://www.npmjs.com/package/@jesec/pkg),  [@jesec/pkg-fetch](https://www.npmjs.com/package/@jesec/pkg-fetch)
**GitHub:** [jesec/pkg](https://github.com/jesec/pkg), [jesec/pkg-fetch](https://github.com/jesec/pkg-fetch)

**Comment by fcastilloec** [comment] 2021-02-23 03:25
@renkei that fork doesn't have any armv7 packages, only arm64. Hopefully, they'll add some, either there or here

**Comment by robertsLando** [comment] 2021-02-23 07:46
You are looking for this? https://github.com/yao-pkg/pkg-binaries

**Comment by fcastilloec** [comment] 2021-02-23 16:57
@robertsLando thanks for the recommendation but they don't have node 14 armv7 binaries... only for older versions of node.

**Comment by robertsLando** [comment] 2021-02-24 07:13
I can build that

**Comment by kdolan** [comment] 2021-02-27 19:26
I also have the issue where make is stuck at 0%. @robertsLando How can I use the armv6 version? I'm targeting node12 on RPi3

**Comment by hipstersmoothie** [comment] 2021-02-28 23:37
@robertsLando Would you be interested in helping maintain this project and moving you awesome docs here?

**Comment by robertsLando** [comment] 2021-03-01 09:09
@hipstersmoothie seems that this project authors are not very active, I would prefer to maintain a fork of this instead

**Comment by leerob** [comment] 2021-03-01 14:37
@robertsLando Hello, myself and @hipstersmoothie will be helping PRs get reviewed / merged on the original!

**Comment by robertsLando** [comment] 2021-03-01 14:52
Ok, It's 2 years I'm waiting for some of my pr to be memrged, both here and on pkg repo. I would be glad to help where I can

**Comment by leerob** [comment] 2021-03-01 15:35
Thank you for tagging me @robertsLando. I know that waiting that long is really frustrating, and I'm sorry about that 🙏

**Comment by ddorsett** [comment] 2021-03-05 21:14
Any word on where to go for something reasonably up to date with the node 14 LTS (14.4.0, the most current pkg for v14 was released 9 months ago)?

**Comment by renkei** [comment] 2021-03-06 10:25
It's really a bad situation. Some years ago, there are some more projects available to generate a self-contained single executables, but all of them are dead, some of them linked to this pkg project. This is the only one now and seems also not to be maintained anymore. Does anyone know an actively maintained alternative?

For me, the need to patch the original Node.js binaries is the biggest problem. Probably, the situation would be immediately solved, once the use case to generate a self-contained executable would be officially supported by Node.js itself. This is what .NET Core and also Deno are offering. For GUI apps built with Node.js you will most likley use Electron, but for headless / server-side stuff, out-of-the-box support by Node.js would be great. Then the community won't need to provide solutions like pkg any longer, with the endless maintainance problems over time since the effort is significant...

**Comment by robertsLando** [comment] 2021-03-06 10:42
I know there was an open issue about this in nodejs repo. If someone could link me to that I could speak with a nodejs dev and ask for this support.

---

Daniel

**Comment by robertsLando** [comment] 2021-03-06 10:47
Maybe it was this one: https://github.com/nodejs/node/issues/26026 

---

Daniel

**Comment by renkei** [comment] 2021-03-06 11:34
@robertsLando 
Thanks for the link. The situation seems to be even worse. No activity for around 2 years, although patch and design document were delivered by the requester...

**Comment by leerob** [comment] 2021-03-07 17:11
Hey @renkei! If you'd like to help contribute, we'd love your assistance 🙌

**Comment by fcastilloec** [comment] 2021-04-12 17:22
There's been a couple of new releases, but they still don't have any armv7 binary provided. At least they have created the patches so it's easier to build from source, even though it takes a really long time if you're doing it on a slow system (like the raspberry pi)
Hopefully @leerob can publish those binaries and this bug can be closed

**Comment by robertsLando** [comment] 2021-04-13 06:20
@fcastilloec we don't plan to support armv7 binaries, but if you want to create a workflow to generate them we could consider it

**Comment by fcastilloec** [comment] 2021-04-13 15:29
@robertsLando thanks for the response. It's too bad about this decision, especially since the majority of Raspberry Pis run on armv7 architecture. I would love to help create a workflow but I don't think I would be able to do it. Hopefully, somebody else can step in and provide this to the big number of people using Raspberry Pis.
I guess this issue should be marked as `won't fix` and/or closed

**Comment by robertsLando** [comment] 2021-04-13 15:36
I could tag @jesec that is working on that and maybe could think about it. BTW rpi also supports arm64 OS FYI

**Comment by fcastilloec** [comment] 2021-04-13 15:44
Yes, it does but by default their official website [offers only armv7](https://www.raspberrypi.org/software/operating-systems/) when trying to download any of the images. To all the people just starting out, it's a lot harder to ask them to reinstall their whole OS just so they can use a module.

**Comment by robertsLando** [comment] 2021-04-13 15:46
I have just give you an alternative fix to your problem, I know it's still on BETA but also feedbacks are good. In the near future there will be less 32 bit OS so we have focused on the most used arch/os for now

**Comment by QuickJack** [comment] 2021-04-30 08:58
It seems that the existing images for armv7 have been removed lately (#174). New images are provided for armv64 only.

It would be nice if the new build would contain armv7 images as well.

**Comment by RogerHardiman** [comment] 2021-04-30 09:36
I'll also add a request for armv7 builds to be in the new release.

There is no release date for the 64 bit version of the Raspberry Pi Foundation's official release OS and even when it is released, I won't be able to upgrade my 32 bit only Pis (Pi version 2).

There are other OS distros for the Pi 3 and Pi 4 that are 64 bit, but they have their quirks especially around GPU related things so I stick to the supported OS, which is bit.

Is this just a case of adding in a workflow change to build for ArmV7 with the right cross compiler toolchain?

**Comment by robertsLando** [comment] 2021-04-30 09:44
@jesec WOuld add amrv7 builds be a pain? Just for linux maybe...

**Comment by jesec** [comment] 2021-04-30 10:13
It is a pain. I am not going to do it.

**Comment by QuickJack** [comment] 2021-04-30 10:58
The architecture armhf (or armv7) is not a relic of the past. It's still a well known embedded platform supported by all major Linux distributions.

**Comment by renkei** [comment] 2021-05-02 18:21
Anyway, I would like to thank all contributors very, very much for bringing the project back to life. Special thanks to jesec! I'm using pkg 5.1 with native modules (better-sqlite3, usb bindings, bluetooth-hci-socket bindings, etc.) and it works like a charm. Since the small icu package is used, I'm able to create self-contained executables packed by 7z with a file size of only  ~10MB. That's great for deployment of headless stuff.

If you really don't want to support ARMv7 anymore then you could put this on the README.md, e.g. a table of supported platforms and architectures should mention Win, Linux, Mac and x64, aarch64 only.

And then you can close this issue with "Won't fix".

**Comment by Hypfer** [comment] 2021-05-03 11:59
Actually, building for armv7 is as simple as slightly modifying the current docker workflow to use
`muslcc/i686:arm-linux-musleabihf` as a base image, adding `-marm` to the cflags and extending the build.ts so that it appends the `--with-arm-fpu` and `--with-arm-float-abi` to the configure parameters if the arch is arm.

> It is a pain. I am absolutely not going to do it.

This is understandable, albeit not true since it's very easy to achieve that. I do respect your decision though.

> 32-bit is a relic of the past. No one should use it in 2021. If you rely on it, either switch to 64-bit OS or upgrade your hardware.

This is wrong. There are currently and there still will be for at _least_ half a decade a lot of existing hosts which are 32 bit arm only which is perfectly fine since most of them aren't even coming close to having 4gb of ram.

For example, my use-case of pkg is to have a single binary application which I can run directly on rooted vacuum robots.
Why should I upgrade the hardware these use? How should I upgrade the hardware these use?

I agree that on desktops and servers, there's no reason to not use 64-bit. Embedded devices or things like raspberry pis which are perfectly capable of doing a _lot_ of stuff even looking five years into the future however do not require that.

IMO there's a lot of potential of pkg wasted by focussing on desktop-only.
Especially considering that having to install a nodejs runtime on a desktop is an insanely easy task.

Sticking to the commercial-application-only use-case and ignoring every other possible usage will be harmful to the project.
Please reconsider

**Comment by schlomo** [comment] 2021-05-03 13:36
I would like to support @Hypfer argument: I actually would think that everybody who needs NodeJS for ARM 32bit does so because they want to run it on some hardware where an upgrade to a more recent 64 bit Linux is simply not possible or not feasible.

So supporting ARMv7 is actually bringing pkg to support all those use cases beyond the well controlled desktop or server ecosystems: embedded, hacked devices, DIY projects, older hardware...

Please do reconsider and help us to use those devices with NodeJS packaged via pkg.

**Comment by fcastilloec** [comment] 2021-05-03 15:26
> Actually, building for armv7 is as simple as slightly modifying the current docker workflow to use
> `muslcc/i686:arm-linux-musleabihf` as a base image, adding `-marm` to the cflags and extending the build.ts so that it appends the `--with-arm-fpu` and `--with-arm-float-abi` to the configure parameters if the arch is arm.

@Hypfer maybe if you can submit a PR to help us all. Even better, host the binaries on your own fork for us to download, since the PR might not get merged if the developers are really not planning on keeping support for `armv7`

**Comment by robertsLando** [comment] 2021-05-03 15:45
If there is a PR I think we can consider to add the binaries, what @jesec said is that he just don't want to keep that supported but there is no problem IMO if someone creates a PR and maintains that part

**Comment by jesec** [comment] 2021-05-03 16:56
One common misconception is that 64-bit is only for devices with more than 4GB memory, or generally more powerful devices. The truth is that 64-bit should be used wherever possible.

The age of 32-bit is long gone, and we are not going to contribute to its staying power in 2021. By dropping support for it, we can better use resources and move the world forward. If you want to stick with relics, you can always use an older version of `pkg`. 

I am not going to maintain any 32-bit arch support in any way, nor will I approve a PR that adds that.

**Comment by Hypfer** [comment] 2021-05-03 17:13
> The truth is that 64-bit should be used wherever possible.

Yes but what about the cases where it's not possible? 
Do I need to throw away my tv, vacuum robot and other appliances because they aren't 64 bit?

I get that you don't want to maintain something that you have no use for and also deem irrelevant, but blatantly ignoring valid use-cases of other people certainly isn't best practice.

Can we at least add some notes somewhere which explain how people can build their own armv7 binaries if it is required for whatever they're trying to accomplish?

**Comment by schlomo** [comment] 2021-05-03 17:21
@jesec sorry to disagree - the point was that in the realm of embedded devices there are many situations where users **cannot** freely exchange the OS. The prime example was the hacked vacuum cleaning robot where one maybe can run something but must continue to use the stock OS as a base.

So your view unfortunately blocks all those wonderful use cases where people do more with their tech than anybody ever imagined.

Even on Raspberry Pi hardware it might not always be so simple to exchange the OS, for example if you depend on a custom RPI solution.

I kindly ask you to reconsider. It will be a very - very - long time before all ARM 32bit hardware will be truly gone from our lives.

**Comment by fcastilloec** [comment] 2021-05-03 17:23
@Hypfer as you probably have seen, there's some issue compiling for armv7 (see https://github.com/vercel/pkg/issues/1148) and support also includes the instruction you're asking for. Your request is something it's probably not going to happen. What should actually happen is to list this breaking change in the Changelog and Releases, so people know what to expect when updating to the newest version that broke compilation for armv7.
You mentioned using Docker with some flags. I'm a very basic user of Docker so I might encounter some error. Nonetheless, I'm still going to try. It'll be very much appreciated if you could fork this repo, implement your changes, and release the compile binaries for people to use.

**Comment by Hypfer** [comment] 2021-05-03 18:37
@jesec
As a maintainer myself, I do get the anger related to people trying to pressure oneself to accept and maintain things.
Still, I do have to say that you've handled this very poorly.

The important thing to point out here is that it is possible to deny requests which don't fit the overall vision of the project without invalidating them. There are of course cases where requests don't make any sense, however this is none of those, which can be clearly seen by the reasons provided as to why using 64-bit isn't always possible.

While there will always be people that don't accept such decisions no matter what, developers are usually open to reason if you actually properly explain `why` the decision was made and provide guidance a to how people can achieve their goal without forcing additional load onto you.

For example, a basic explaination how to locally build the binaries and pointing `pkg` to them would be more than enough.


Especially considering that `pkg` just came back to life after being stale for years, it is only a matter of time until it returns to that unmaintained state if this is how things will be handled in the future, since alienating other devs just for the sake of it certainly won't help building and maintaining a community.


Be that as it may, I've pushed the changes relevant to my use-case to a fork of pkg-fetch which can be found here:
https://github.com/Hypfer/pkg-fetch
No warranties or anything. It's just what my project needs

What I'd like to point out though is that it's very clear from the diff that there are little changes necessary to get armv7 to work. The rest is just additional stuff which i need personally.
Even though I do respect your decision, I fail to see how that armv7 build causes any overhead.

It's a less than 10 LoC patch with - as far as i can tell - no impact to the rest of the architecture.

**Comment by jesec** [comment] 2021-05-14 14:15
I do see some merits in the embedded case. However, as you can see, troubles with armv7 are already popping up (vercel/pkg#1148), and none of us has the necessary equipment to deal with those issues. As a result, practically we would not be able to properly maintain the architecture. 

Nonetheless, I am open to some limited, best-effort and non-semver-protected support for armv7 on one platform only. Currently there are three Linux platforms: `linux`, `linuxstatic` and `alpine`. IMO `linuxstatic` is the best option here.

**Comment by Hypfer** [comment] 2021-05-14 18:44
Glad you've reconsidered :)

> IMO linuxstatic is the best option here.

Yep definitely. That should be sufficent for all relevant use-cases

**Comment by jesec** [comment] 2021-05-28 16:21
@Hypfer Would you mind to do a PR with the minimal required changes to Dockerfile and workflow?

**Comment by QuickJack** [comment] 2021-06-15 13:38
That sounds great. Now there's a  node-v14.17.0-linuxstatic-armv7 image under Releases. However, trying to use that image results in the following output:

```
pkg -t node14-linuxstatic-armv7 index.js -o authd
> pkg@5.2.1
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.17.0-linuxstatic-armv7  [                    ] 0%
> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.1","name":"node-v14.17.0-linuxstatic-armv7"}
> Building base binary from source:
  built-v14.17.0-linuxstatic-armv7
> Error! Not able to build for 'linuxstatic' here, only for 'linux'
```

**Comment by Hypfer** [comment] 2021-06-15 14:46
@QuickJack 
You'll need to name it correctly.

pkg uses either `fetched-v14.17.0-linuxstatic-armv7` which must pass the checksum check or `built-v14.17.0-linuxstatic-armv7` which doesn't.

**Comment by schlomo** [comment] 2021-06-15 17:21
See vercel/pkg#1220 I think the root cause is that pkg is not yet using pkg-fetch@3.2

**Comment by QuickJack** [comment] 2021-06-15 19:54
@Hypfer Yes, it works if the image and the checksum file are downloaded manually to ~/.pkg-cache/v3.1. However, the automatic download does not work yet.

**Comment by QuickJack** [comment] 2021-06-18 07:34
> See [vercel/pkg#1220](https://github.com/vercel/pkg/issues/1220) I think the root cause is that pkg is not yet using pkg-fetch@3.2

It should be as simple as updating the dependencies section of package.json to fix this issue. Is there a reason why pkg is still referencing pkg-fetch@3.1.1?

**Comment by Hypfer** [comment] 2021-06-18 08:31
Because there was no release of pkg since then.

I assume it's because CI is failing for https://github.com/vercel/pkg/pull/1215 and nobody had time to investigate that yet.

**Comment by QuickJack** [comment] 2021-06-18 11:01
Well, pkg@5.2.1 appears under Releases in GitHub and it's installed by default using `npm install -g pkg`.

**Comment by Hypfer** [comment] 2021-06-18 11:06
That is correct.
pkg@5.2.1 doesn't reference pkg-fetch@3.2 because the PR for the dependency bump is still open since the CI is failing.

**Comment by knro** [comment] 2021-09-12 17:19
I'm getting a similar error to @QuickJack using pkg@5.3.2 and pkg-fetch@3.2.3 when trying to run

pkg -t node14-linuxstatic-armv7 index.js

```
> pkg@5.3.2
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v14.17.6-linux-armv7        [                    ] 0%
> Error! 404: Not Found
> Not found in remote cache:
  {"tag":"v3.2","name":"node-v14.17.6-linux-armv7"}
> Building base binary from source:
  built-v14.17.6-linux-armv7
> Cloning Node.js repository from GitHub...
Cloning into bare repository 'node/.git'...

```

The first time I ran this, it downloaded the package but then it proceeded to try to download the non-static version. I checked the checksum and it's correct:

`08cb7708a9c3cb68d828aa0dc383700d84cca6571102a851487520357bfe6202  /home/pi/.pkg-cache/v3.2/fetched-v14.17.6-linuxstatic-armv7
`

Any ideas on what to try next?

**Comment by QuickJack** [comment] 2021-09-12 18:12
It seems that you are trying to do a native build directly on the PI which is not supported. I have created https://github.com/vercel/pkg/pull/1276 which fixes native builds. Can you give it a try?

**Closed** 2022-01-28 00:00 UTC
