### ISSUE TITLE
Library for arm64 binaries and others not supported platforms

### ISSUE THREAD

**Issue by robertsLando** [vercel/pkg-fetch#53] opened 2018-12-11 14:40 UTC
I have created a github repo to place resources that are not aviable by default on pkg and that need to be compiled. 

https://github.com/robertsLando/pkg-binaries

**Comment by danawoodman** [comment] 2019-09-30 23:46
@igorklopov plans to update binaries to support arm64 and later versions of node? Having users build (which seems to take hours) is unfortunate :/

**Comment by hipstersmoothie** [comment] 2021-02-28 23:27
@leerob this is a dupe of #35 and can be closed

**Closed** 2021-03-01 14:44 UTC
